import type { ImageSourcePropType } from 'react-native';
import type { CardDefinition, CardType } from '../../domain/card';
import { baseCardId } from '../../logic/cards';

/**
 * カード id（強化前）ごとのイラスト。ドメインの CardDefinition は画像を知らないよう、UI 側で対応付ける。
 * 画像は AI 画像生成（カラフルなカートゥーン調）で作り、scripts/resize-art.mjs で 320×240 に縮小している。
 */
const CARD_ART: Record<string, ImageSourcePropType> = {
  strike: require('../../../assets/cards/strike.jpg'),
  defend: require('../../../assets/cards/defend.jpg'),
  'strike-verdant': require('../../../assets/cards/strike-verdant.jpg'),
  'defend-verdant': require('../../../assets/cards/defend-verdant.jpg'),
  'twin-strike': require('../../../assets/cards/twin-strike.jpg'),
  'pommel-strike': require('../../../assets/cards/pommel-strike.jpg'),
  'iron-wave': require('../../../assets/cards/iron-wave.jpg'),
  'heavy-blade': require('../../../assets/cards/heavy-blade.jpg'),
  clothesline: require('../../../assets/cards/clothesline.jpg'),
  hemokinesis: require('../../../assets/cards/hemokinesis.jpg'),
  anger: require('../../../assets/cards/anger.jpg'),
  cleave: require('../../../assets/cards/cleave.jpg'),
  thunderclap: require('../../../assets/cards/thunderclap.jpg'),
  'flurry-form': require('../../../assets/cards/flurry-form.jpg'),
  whirlwind: require('../../../assets/cards/whirlwind.jpg'),
  'shrug-it-off': require('../../../assets/cards/shrug-it-off.jpg'),
  'seeing-red': require('../../../assets/cards/seeing-red.jpg'),
  bloodletting: require('../../../assets/cards/bloodletting.jpg'),
  'battle-trance': require('../../../assets/cards/battle-trance.jpg'),
  offering: require('../../../assets/cards/offering.jpg'),
  flex: require('../../../assets/cards/flex.jpg'),
  inflame: require('../../../assets/cards/inflame.jpg'),
  metallicize: require('../../../assets/cards/metallicize.jpg'),
  bash: require('../../../assets/cards/bash.jpg'),
  intimidate: require('../../../assets/cards/intimidate.jpg'),
  uppercut: require('../../../assets/cards/uppercut.jpg'),
  shockwave: require('../../../assets/cards/shockwave.jpg'),
  'body-slam': require('../../../assets/cards/body-slam.jpg'),
  'steadfast-guard': require('../../../assets/cards/steadfast-guard.jpg'),
  barricade: require('../../../assets/cards/barricade.jpg'),
  entrench: require('../../../assets/cards/entrench.jpg'),
  'searing-decree': require('../../../assets/cards/searing-decree.jpg'),
  'heat-up': require('../../../assets/cards/heat-up.jpg'),
  'soul-flame': require('../../../assets/cards/soul-flame.jpg'),
  'ultimate-strike': require('../../../assets/cards/ultimate-strike.jpg'),
  'ultimate-defend': require('../../../assets/cards/ultimate-defend.jpg'),
  'crimson-phoenix': require('../../../assets/cards/crimson-phoenix.jpg'),
  'thousand-year-tree': require('../../../assets/cards/thousand-year-tree.jpg'),
  'seed-arrow': require('../../../assets/cards/seed-arrow.jpg'),
  'seed-scatter': require('../../../assets/cards/seed-scatter.jpg'),
  'vine-bind': require('../../../assets/cards/vine-bind.jpg'),
  'full-bloom': require('../../../assets/cards/full-bloom.jpg'),
  'rampant-growth': require('../../../assets/cards/rampant-growth.jpg'),
  'forest-wrath': require('../../../assets/cards/forest-wrath.jpg'),
  overgrowth: require('../../../assets/cards/overgrowth.jpg'),
  'thorn-armor': require('../../../assets/cards/thorn-armor.jpg'),
  'thorn-wall': require('../../../assets/cards/thorn-wall.jpg'),
  verdure: require('../../../assets/cards/verdure.jpg'),
  'great-tree-blessing': require('../../../assets/cards/great-tree-blessing.jpg'),
  sunbeam: require('../../../assets/cards/sunbeam.jpg'),
  'gale-arrows': require('../../../assets/cards/gale-arrows.jpg'),
  'world-tree-seed': require('../../../assets/cards/world-tree-seed.jpg'),
  'vine-lash': require('../../../assets/cards/vine-lash.jpg'),
  'vital-shot': require('../../../assets/cards/vital-shot.jpg'),
  'aimed-shot': require('../../../assets/cards/aimed-shot.jpg'),
  'whip-storm': require('../../../assets/cards/whip-storm.jpg'),
  'whip-flurry': require('../../../assets/cards/whip-flurry.jpg'),
  'thorn-whip': require('../../../assets/cards/thorn-whip.jpg'),
  'quick-shot': require('../../../assets/cards/quick-shot.jpg'),
  'nocking-rhythm': require('../../../assets/cards/nocking-rhythm.jpg'),
  'quickdraw-stance': require('../../../assets/cards/quickdraw-stance.jpg'),
  'thousand-arrows': require('../../../assets/cards/thousand-arrows.jpg'),
  'wind-read': require('../../../assets/cards/wind-read.jpg'),
  'arrow-rain': require('../../../assets/cards/arrow-rain.jpg'),
  'double-shot': require('../../../assets/cards/double-shot.jpg'),
  'focused-breath': require('../../../assets/cards/focused-breath.jpg'),
  tailwind: require('../../../assets/cards/tailwind.jpg'),
  'deep-roots': require('../../../assets/cards/deep-roots.jpg'),
  'spore-cloud': require('../../../assets/cards/spore-cloud.jpg'),
  'mistletoe-harvest': require('../../../assets/cards/mistletoe-harvest.jpg'),
  'withering-touch': require('../../../assets/cards/withering-touch.jpg'),
  'whip-crack': require('../../../assets/cards/whip-crack.jpg'),
  'lash-chain': require('../../../assets/cards/lash-chain.jpg'),
  'snare-whip': require('../../../assets/cards/snare-whip.jpg'),
  'hunters-mark': require('../../../assets/cards/hunters-mark.jpg'),
  'vine-stance': require('../../../assets/cards/vine-stance.jpg'),
  'mistletoe-lash': require('../../../assets/cards/mistletoe-lash.jpg'),
  'strangling-vine': require('../../../assets/cards/strangling-vine.jpg'),
  'jade-serpent-lash': require('../../../assets/cards/jade-serpent-lash.jpg'),
  arrow: require('../../../assets/cards/arrow.jpg'),
  'arrow-dance': require('../../../assets/cards/arrow-dance.jpg'),
  'quick-nock': require('../../../assets/cards/quick-nock.jpg'),
  'nock-and-loose': require('../../../assets/cards/nock-and-loose.jpg'),
  'spent-volley': require('../../../assets/cards/spent-volley.jpg'),
  'keen-arrowheads': require('../../../assets/cards/keen-arrowheads.jpg'),
  'scatter-stance': require('../../../assets/cards/scatter-stance.jpg'),
  'quiver-keep': require('../../../assets/cards/quiver-keep.jpg'),
  'endless-quiver': require('../../../assets/cards/endless-quiver.jpg'),
  'hunters-focus': require('../../../assets/cards/hunters-focus.jpg'),
  'hunting-instinct': require('../../../assets/cards/hunting-instinct.jpg'),
  'frost-edge': require('../../../assets/cards/frost-edge.jpg'),
  'ice-lances': require('../../../assets/cards/ice-lances.jpg'),
  'leaf-flash': require('../../../assets/cards/leaf-flash.jpg'),
  'leaf-storm': require('../../../assets/cards/leaf-storm.jpg'),
  'flame-slash': require('../../../assets/cards/flame-slash.jpg'),
  'enchant-fire': require('../../../assets/cards/enchant-fire.jpg'),
  'enchant-water': require('../../../assets/cards/enchant-water.jpg'),
  'enchant-grass': require('../../../assets/cards/enchant-grass.jpg'),
  trip: require('../../../assets/cards/trip.jpg'),
  exploit: require('../../../assets/cards/exploit.jpg'),
  dropkick: require('../../../assets/cards/dropkick.jpg'),
  'brand-burst': require('../../../assets/cards/brand-burst.jpg'),
  'weak-point': require('../../../assets/cards/weak-point.jpg'),
  impervious: require('../../../assets/cards/impervious.jpg'),
  'shield-shatter': require('../../../assets/cards/shield-shatter.jpg'),
  juggernaut: require('../../../assets/cards/juggernaut.jpg'),
  'rise-from-ashes': require('../../../assets/cards/rise-from-ashes.jpg'),
  'blood-price': require('../../../assets/cards/blood-price.jpg'),
  'crimson-avatar': require('../../../assets/cards/crimson-avatar.jpg'),
  'burning-blood': require('../../../assets/cards/burning-blood.jpg'),
  rampage: require('../../../assets/cards/rampage.jpg'),
  devour: require('../../../assets/cards/devour.jpg'),
  'honed-blade': require('../../../assets/cards/honed-blade.jpg'),
  'tempered-shield': require('../../../assets/cards/tempered-shield.jpg'),
  burn: require('../../../assets/cards/burn.jpg'),
  'tangling-vine': require('../../../assets/cards/tangling-vine.jpg'),
  'ice-shard': require('../../../assets/cards/ice-shard.jpg'),
  scrap: require('../../../assets/cards/scrap.jpg'),
};

/** イラストの隅に重ねる種類の紋章。小さな手札でも種類がひと目で分かるように。 */
export const CARD_TYPE_EMBLEM: Record<CardType, string> = {
  attack: '⚔️',
  skill: '🛡️',
  power: '✨',
  status: '💢',
};

/** 強化後のカードも強化前と同じ絵。絵が未登録のカードは undefined（種類の色だけの枠になる）。 */
export function cardArt(card: CardDefinition): ImageSourcePropType | undefined {
  return CARD_ART[card.art ?? baseCardId(card.id)];
}
